### ISSUE TITLE
ImportError: No module named flask_restful

### ISSUE THREAD

**Issue by ch40s** [tomchop/malcom#38]
I get the following error, do you think something goes wrong with flash? I have Flash 0.10.1 installed.

```
Traceback (most recent call last):
  File "./malcom.py", line 112, in <module>
    from Malcom.web.webserver import MalcomWeb
  File "/opt/malcom/Malcom/web/webserver.py", line 120, in <module>
    from Malcom.web.api import malcom_api
  File "/opt/malcom/Malcom/web/api.py", line 7, in <module>
    from flask_restful import Resource, reqparse, Api
ImportError: No module named flask_restful
```

**Comment by tomchop** [comment]
There's a missing line in requirements.txt
