### ISSUE TITLE
Error mongodb

### ISSUE THREAD

**Issue by jarmouz** [tomchop/malcom#42]
Hello, 

After run this command ./malcom.py -c malcom.conf I have this error

Detected interfaces:
eth3:   192.168.74.146
eth2:   Not defined
eth1:   192.168.74.144
eth0:   192.168.74.148
[+] Starting sniffer...
[+] Successfully loaded sniffer directory: /root/malcom/Malcom/sniffer
[+] Starting TLS proxy on port 9000
Traceback (most recent call last):
  File "./malcom.py", line 79, in <module>
    setup.sniffer_engine = netsniffer.SnifferEngine(setup, yara_rules=yara_rules)
  File "/root/malcom/Malcom/networking/netsniffer.py", line 56, in __init__
    self.model = Model()
  File "/root/malcom/Malcom/model/model.py", line 39, in __init__
    self._connection = MongoClient()
  File "/root/malcom/env-malcom/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused

**Comment by tomchop** [comment]
Are you sure the `mobgodb` server is up and running?

**Comment by jarmouz** [comment]
Thank you :)
