### ISSUE TITLE
problem when running malcom 

### ISSUE THREAD

**Issue by user597** [tomchop/malcom#45]
Hi 
when I try to run malcom, I get this error message. I used the default configuration file

```
./malcom.py -c malcom.conf
===== Malcom 1.3a - Malware Communications Analyzer =====

Traceback (most recent call last):
  File "./malcom.py", line 59, in <module>
    setup.load_config(args)
  File "~/Malcom/config/malconf.py", line 13, in load_config
    self.parse_command_line(args)
  File "~/Malcom/config/malconf.py", line 30, in parse_command_line
    self.parse_config_file(args.config)
  File "~/Malcom/config/malconf.py", line 73, in parse_config_file
    self['MODULES_DIR'] = config.get('sniffer', 'modules_dir')
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'modules_dir' in section: 'sniffer'
```

**Comment by user597** [comment]
Now it works , I added this line in "[sniffer]"  block
```
modules_dir = Malcom
```

**Comment by tomchop** [comment]
Yes, there was a change in the default config file.
