### ISSUE TITLE
Malcom crashes when starting a sniffing session

### ISSUE THREAD

**Issue by srilumpa** [tomchop/malcom#48]
I have an issue when trying to create a sniffing session.

When I create a sniffer, whether a live one or through a pcap file, the following log appears and no result is shown through the web interface.

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mad/Documents/dev/malcom_perso/Malcom/sniffer/netsniffer.py", line 250, in run
    self.load_pcap()
  File "/home/mad/Documents/dev/malcom_perso/Malcom/sniffer/netsniffer.py", line 227, in load_pcap
    self.sniff(stopper=self.stop_sniffing, filter=self.filter, prn=self.handlePacket, stopperTimeout=1, offline=self.engine.setup['SNIFFER_DIR']+"/"+filename)
  File "/home/mad/Documents/dev/malcom_perso/Malcom/sniffer/netsniffer.py", line 653, in sniff
    sel = select([s], [], [], remainStopper)
TypeError: 'module' object is not callable
```

I'm probably missing something but can't see what. Does an additional module is needed for this to work?

**Comment by tomchop** [comment]
Which version of Scapy are you running? Did you install it as explained in the README?

**Comment by srilumpa** [comment]
No, I installed through pip. I uninstalled it with pip and then installed it again following the README and it worked.

**Comment by tomchop** [comment]
Good to hear :)
