### ISSUE TITLE
errors on startup

### ISSUE THREAD

**Issue by scalefree** [tomchop/malcom#53]
I installed Malcom as a Docker container in a new, stock Ubuntu 14.04 VM.  When I try to run it using the syntax from the Docker part of the README.md (docker run -p 8080:8080 -d --name malcom tomchop/malcom-automatic) I get this set of errors:

 * Starting database mongodb
   ...done.
Starting redis-server: redis-server.
TERM environment variable not set.
===== Malcom 1.3a - Malware Communications Analyzer =====

Detected interfaces:
eth0:	172.17.0.3
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: No route found for IPv6 destination :: (no default route?)
[+] Starting sniffer...
[+] Successfully loaded sniffer directory: /opt/malcom/Malcom/sniffer/captures
[+] Starting TLS proxy on port 9000
Traceback (most recent call last):
  File "./malcom.py", line 79, in <module>
    setup.sniffer_engine = netsniffer.SnifferEngine(setup)
  File "/opt/malcom/Malcom/sniffer/netsniffer.py", line 51, in __init__
    self.model = Model(self.setup)
  File "/opt/malcom/Malcom/model/model.py", line 46, in __init__
    read_preference=read_pref[db_setup.get('READ_PREF', 'PRIMARY')])
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused

**Comment by sbilly** [comment]
===== Malcom 1.3a - Malware Communications Analyzer =====

Traceback (most recent call last):
  File "./malcom.py", line 59, in <module>
    setup.load_config(args)
  File "/opt/malcom/Malcom/config/malconf.py", line 15, in load_config
    self.parse_command_line(args)
  File "/opt/malcom/Malcom/config/malconf.py", line 34, in parse_command_line
    self.parse_config_file(args.config)
  File "/opt/malcom/Malcom/config/malconf.py", line 65, in parse_config_file
    self['SKIP_WHITELISTED'] = config.getboolean('analytics', 'skip_whitelisted')
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'skip_whitelisted' in section: 'analytics'

**Comment by tomchop** [comment]
@sbilly: Should be fixed in f2ba3cbf5805f9f0f657cb3a6e1c6a417c465d93
@scalefree: this means that the mongodb daemon is not running. Are you still getting the same error with latest commig?

**Comment by tomchop** [comment]
Any news on this?

**Comment by f1b3ropt1k** [comment]
sorry have not had a chance to revisit it.  Been traveling and just
generally busy :)
