### ISSUE TITLE
My struggles with malcom

### ISSUE THREAD

**Issue by DigiAngel** [tomchop/malcom#60]
First off Tom this is a great app.  I really enjoy it and it's very unique.  That being said here are my struggles with it currently. 

So, my setup is this is behind a firewall and IDS...and as soon as Malcom starts with feeds my IDS lights up all over the place.  So, ultimately, my goal is to have Malcom without the feeds options.  Things I've tried:

1.  From source.  The first sticking point is cryptography==0.7.2 on debian/ubuntu won't install at all.  Removing the line and running the pip command auto installs cryptography-2.0.3.  After changing feeds = false here's what I get after the run:
~~~
{'MAX_WORKERS': '12', 'SKIP_TAGS': 'whitelisted', 'ACTIVATED': 'true'}
{'WEB': True, 'LISTEN_PORT': 8080, 'ANALYTICS': True, 'ACTIVATED': 'true', 'AUTH': False, 'MAX_WORKERS': 12, 'SKIP_TAGS': ['whitelisted'], 'VERSION': '1.3a', 'LISTEN_INTERFACE': '0.0.0.0'}
Detected interfaces:
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: No route found for IPv6 destination :: (no default route?)
[+] Starting sniffer...
[+] Successfully loaded sniffer directory: /opt/malcom/Malcom/sniffer/captures
Traceback (most recent call last):
  File "./malcom.py", line 79, in <module>
    setup.sniffer_engine = netsniffer.SnifferEngine(setup)
  File "/opt/malcom/Malcom/sniffer/netsniffer.py", line 41, in __init__
    from Malcom.sniffer.tlsproxy.tlsproxy import MalcomTLSProxy
  File "/opt/malcom/Malcom/sniffer/tlsproxy/tlsproxy.py", line 9, in <module>
    from twisted.internet import defer, ssl
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 3, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'
~~~

after this you can't even run pip anymore:
~~~
Traceback (most recent call last):
  File "/opt/malcom/env-malcom/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/opt/malcom/env-malcom/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/opt/malcom/env-malcom/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/opt/malcom/env-malcom/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/opt/malcom/env-malcom/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/opt/malcom/env-malcom/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/opt/malcom/env-malcom/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/opt/malcom/env-malcom/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 3, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/malcom/env-malcom/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'
~~~

the entire virtual-env seems destroyed.

2.  Docker.  So the docker image works fine, however, again, as soon as it's fired up it sprays all over the IDS causing a lot of issues.  I've tried: routing all the traffic over tor, blocking dns.  What I'd LIKE to do is modify the malcom.conf file within the but I haven't been successful.

Tom, is there any way you can add a feature in the web page configuration to disable feeds?  Just...SOMETHING that will stop the feeds.  Thank you

**Comment by tomchop** [comment]
By `feeds = false` I believe you mean 

```
[feeds]
activated = false
```

In `malcom.conf`?

There seems to be two different issues with your setup. One with the feeds loading, which you don't want, the other one with Python's `cryptography` module. The thing is, deactivating feeds should not raise an OpenSSL error in the sniffer. My guess is this is probably due to the fact that the libs are pretty outdated and don't match the binaries in recent versions of ubuntu.

Also, I find it strange that feeds are what trigger our IDS since they only fetch content from "legit" websites (zeustracker, etc.). Is your IDS configured to trigger when you visit sites like zeustracker? I can see analytics triggering IDSs since they e.g. resolve hostnames that are known to be bad.

What I can recommend:

* Try changing the Dockerfile to deactivate feeds (or analytics), and then try running the Docker image again. 
* Since the requirements file is from (literally) years ago, try clearing the version numbers and `pip install`ing them again. This should install the most recent versions of the python libs, matching with your system's binaries. Mind you, the python APIs may have changed since and if Malcom's code is using old APIs, you will get a whole new set of errors.
* What ubuntu version are you running Malcom on? The install was tested with Ubuntu 14.04 LTS, so it might be worth rolling back to that version (especially if you're only using that VM for Malcom)

Let me know what worked for you!

**Comment by DigiAngel** [comment]
Thanks Tom!  So this is latest...Debian Stretch.  I would LOVE to change the dockerfile...how?  I've followed this:

~~~
    $ sudo docker pull tomchop/malcom-automatic
    $ sudo docker run -p 8080:8080 -d --name malcom tomchop/malcom-automatic
~~~
How do I crack into the dockerfile?  Thanks again Tom.

As for the alerts...:)
~~~
Sep 27 06:53:46  snort[14262]: [1:2022332:5] ET POLICY DNS Query to .onion proxy Domain (onion.link) [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} x.x.x.x:47757 -> 8.8.8.8:53
Sep 27 06:53:46  snort[14262]: [1:2022332:5] ET POLICY DNS Query to .onion proxy Domain (onion.link) [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} x.x.x.x:59923 -> 8.8.8.8:53
Sep 27 06:53:46  snort[14262]: [1:2022332:5] ET POLICY DNS Query to .onion proxy Domain (onion.link) [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} x.x.x.x:52184 -> 8.8.8.8:53
Sep 27 06:53:46  snort[14262]: [1:2022332:5] ET POLICY DNS Query to .onion proxy Domain (onion.link) [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} x.x.x.x:42927 -> 8.8.8.8:53
Sep 27 07:04:10  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:39140 -> 8.8.8.8:53
Sep 27 07:04:10  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:55809 -> 8.8.8.8:53
Sep 27 07:04:10  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:34905 -> 8.8.8.8:53
Sep 27 07:04:10  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:39018 -> 8.8.8.8:53
Sep 27 07:04:14  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:43579 -> 8.8.8.8:53
Sep 27 07:04:15  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:47099 -> 8.8.8.8:53
Sep 27 07:04:15  snort[14262]: [1:2018316:4] ET TROJAN Zeus GameOver Possible DGA NXDOMAIN Responses [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:39206
Sep 27 07:04:15  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:55551 -> 8.8.8.8:53
Sep 27 07:04:16  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:39314 -> 8.8.8.8:53
Sep 27 07:04:21  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:33219 -> 8.8.8.8:53
Sep 27 07:04:21  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:33814 -> 8.8.8.8:53
Sep 27 07:04:21  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:40056 -> 8.8.8.8:53
Sep 27 07:04:21  snort[14262]: [1:2012811:2] ET DNS Query to a .tk domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:56996 -> 8.8.8.8:53
Sep 27 07:04:27  snort[14262]: [1:2012327:4] ET MALWARE All Numerical .cn Domain Likely Malware Related [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:43055 -> 8.8.8.8:53
Sep 27 07:04:27  snort[14262]: [1:2012327:4] ET MALWARE All Numerical .cn Domain Likely Malware Related [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:54089 -> 8.8.8.8:53
Sep 27 07:04:27  snort[14262]: [1:2012327:4] ET MALWARE All Numerical .cn Domain Likely Malware Related [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:43327 -> 8.8.8.8:53
Sep 27 07:04:28  snort[14262]: [1:2012327:4] ET MALWARE All Numerical .cn Domain Likely Malware Related [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:49103 -> 8.8.8.8:53
Sep 27 07:04:33  snort[14262]: [1:2016104:3] ET TROJAN DNS Reply for unallocated address space - Potentially Malicious 1.1.1.0/24 [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:35872
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:55354
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:47098
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:60270
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:49303
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:34329
Sep 27 07:04:36  snort[14262]: [1:31600:1] BLACKLIST DNS reverse lookup response for known malware domain spheral.ru - Win.Trojan.Glupteba [Classification: A Network Trojan was Detected] [Priority: 1] {UDP} 8.8.8.8:53 -> x.x.x.x:56757
Sep 27 07:04:37  snort[14262]: [1:2013743:3] ET INFO DYNAMIC_DNS Query to a Suspicious no-ip Domain [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:47180 -> 8.8.8.8:53
Sep 27 07:04:37  snort[14262]: [1:2013743:3] ET INFO DYNAMIC_DNS Query to a Suspicious no-ip Domain [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:49468 -> 8.8.8.8:53
Sep 27 07:04:37  snort[14262]: [1:2013743:3] ET INFO DYNAMIC_DNS Query to a Suspicious no-ip Domain [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:55966 -> 8.8.8.8:53
Sep 27 07:04:37  snort[14262]: [1:2013743:3] ET INFO DYNAMIC_DNS Query to a Suspicious no-ip Domain [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:34588 -> 8.8.8.8:53
Sep 27 07:04:37  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:59686 -> 8.8.8.8:53
Sep 27 07:04:38  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:50453 -> 8.8.8.8:53
Sep 27 07:04:39  snort[14262]: [1:2012758:4] ET INFO DYNAMIC_DNS Query to *.dyndns. Domain [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:52745 -> 8.8.8.8:53
Sep 27 07:04:39  snort[14262]: [1:2012758:4] ET INFO DYNAMIC_DNS Query to *.dyndns. Domain [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:57084 -> 8.8.8.8:53
Sep 27 07:04:39  snort[14262]: [1:2012758:4] ET INFO DYNAMIC_DNS Query to *.dyndns. Domain [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:33195 -> 8.8.8.8:53
Sep 27 07:04:39  snort[14262]: [1:2012758:4] ET INFO DYNAMIC_DNS Query to *.dyndns. Domain [Classification: Misc activity] [Priority: 3] {UDP} x.x.x.x:50832 -> 8.8.8.8:53
Sep 27 07:04:48  snort[14262]: [1:2016778:4] ET DNS Query to a *.pw domain - Likely Hostile [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} x.x.x.x:56880 -> 8.8.8.8:53
~~~

**Comment by tomchop** [comment]
Yup, this is probably the analytics resolving domains that have been fetched with the feeds. Cutting off the feeds won't solve the issue, since any other hostname you add to Malcom (e.g. those you sniff) will be eventually analysed (and therefore resolved, etc.). What you want is to disable analytics (by editing the config file).

As for the dockerfile you can just clone the repo `cd` into it, tweak the Dockerfile to add a `sed` command (similar to the one in [line 31](https://github.com/tomchop/malcom/blob/master/Dockerfile#L31) to replace the `true` by `false`.

That will solve your IDS problem. If you still run into things with the python cryptography module, then I see no other "quick" fix than to roll back to Ubuntu 14.04 :(

**Comment by DigiAngel** [comment]
Ok cool...so looks like I'll need to shut down analytics and try sweet.  I'll give this a shot and report my findings.  Thanks again!

**Comment by DigiAngel** [comment]
Ok...so I'm super close...my last bit is changing the lines via sed.  It looks like I can't just change activated = true as that would nuke more then what I need.  How do I change:
~~~
[feeds]
activated = true

[analytics]
activated = true
~~~
in one shot to false?  Thank you.!

**Comment by tomchop** [comment]
You can use `sed '5s/true/false' config` where `5` is the line number you want the replacement to occur.

**Comment by DigiAngel** [comment]
Success!  Thank you so much.  My process:
~~~
git clone https://github.com/tomchop/malcom.git malcom
cd malcom
~~~
add
~~~
RUN sed -i -e '11s/true/false/' -e '17s/true/false/' malcom.conf
~~~
under the "scheduler" line to the DockerFile.  Then:
~~~
sudo docker build - < Dockerfile
~~~
once complete get image ID with:
~~~
sudo docker image list
~~~
with the IMAGE_ID activate it with:
~~~
sudo docker run -p 8080:8080 -d IMAGE_ID
~~~
then get the container ID with:
~~~
sudo docker ps -a
~~~
Finally start the container with:
~~~
sudo docker start CONTAINER_ID
~~~

Thanks again Tom!

**Comment by tomchop** [comment]
Cool! Thanks for documenting this :) Closing out the issue.
